// Sample Event Data for BookMyShow Enhanced Sorting
// This file contains mock data for demonstration purposes

const events = [
    {
        id: 1,
        title: "Pathaan",
        genre: "movie",
        subGenre: "Action/Thriller",
        language: "Hindi",
        venue: "PVR Orion Mall",
        address: "Dr Rajkumar Road, Rajajinagar",
        location: { lat: 12.9876, lng: 77.5568 },
        basePrice: 250,
        rating: 4.5,
        popularity: 95,
        accessible: true,
        timeSlots: ["10:00 AM", "1:30 PM", "5:00 PM", "8:30 PM"],
        icon: "🎬"
    },
    {
        id: 2,
        title: "Jawan",
        genre: "movie",
        subGenre: "Action/Drama",
        language: "Hindi",
        venue: "INOX Mantri Square",
        address: "Malleshwaram",
        location: { lat: 13.0082, lng: 77.5690 },
        basePrice: 300,
        rating: 4.7,
        popularity: 92,
        accessible: true,
        timeSlots: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
        icon: "🎬"
    },
    {
        id: 3,
        title: "Kantara",
        genre: "movie",
        subGenre: "Action/Drama",
        language: "Kannada",
        venue: "Cinepolis Royal Meenakshi Mall",
        address: "Bannerghatta Road",
        location: { lat: 12.8926, lng: 77.5988 },
        basePrice: 180,
        rating: 4.8,
        popularity: 88,
        accessible: true,
        timeSlots: ["10:30 AM", "2:00 PM", "5:30 PM", "9:00 PM"],
        icon: "🎬"
    },
    {
        id: 4,
        title: "Oppenheimer",
        genre: "movie",
        subGenre: "Biography/Drama",
        language: "English",
        venue: "PVR Forum Mall",
        address: "Koramangala",
        location: { lat: 12.9346, lng: 77.6094 },
        basePrice: 350,
        rating: 4.9,
        popularity: 85,
        accessible: false,
        timeSlots: ["12:00 PM", "3:30 PM", "7:00 PM", "10:30 PM"],
        icon: "🎬"
    },
    {
        id: 5,
        title: "Arijit Singh Live",
        genre: "concert",
        subGenre: "Bollywood/Romantic",
        language: "Hindi",
        venue: "Jayamahal Palace Grounds",
        address: "Jayamahal Road",
        location: { lat: 12.9991, lng: 77.5922 },
        basePrice: 1500,
        rating: 4.6,
        popularity: 98,
        accessible: true,
        timeSlots: ["7:00 PM"],
        icon: "🎤"
    },
    {
        id: 6,
        title: "Zakir Khan: Tathastu",
        genre: "comedy",
        subGenre: "Stand-up Comedy",
        language: "Hindi",
        venue: "Chowdiah Memorial Hall",
        address: "Malleswaram",
        location: { lat: 13.0047, lng: 77.5651 },
        basePrice: 500,
        rating: 4.4,
        popularity: 82,
        accessible: true,
        timeSlots: ["7:30 PM", "9:30 PM"],
        icon: "😂"
    },
    {
        id: 7,
        title: "Hamlet by Rangayana",
        genre: "theatre",
        subGenre: "Classic Drama",
        language: "Kannada",
        venue: "Ranga Shankara",
        address: "JP Nagar",
        location: { lat: 12.9015, lng: 77.5832 },
        basePrice: 300,
        rating: 4.5,
        popularity: 65,
        accessible: true,
        timeSlots: ["3:00 PM", "7:00 PM"],
        icon: "🎭"
    },
    {
        id: 8,
        title: "RCB vs CSK",
        genre: "sports",
        subGenre: "Cricket - IPL",
        language: "Multi",
        venue: "M. Chinnaswamy Stadium",
        address: "Cubbon Park, MG Road",
        location: { lat: 12.9789, lng: 77.5996 },
        basePrice: 800,
        rating: 4.7,
        popularity: 99,
        accessible: true,
        timeSlots: ["7:30 PM"],
        icon: "🏏"
    },
    {
        id: 9,
        title: "Diljit Dosanjh Live",
        genre: "concert",
        subGenre: "Punjabi/Bollywood",
        language: "Punjabi",
        venue: "NICE Grounds",
        address: "Tumkur Road",
        location: { lat: 13.0445, lng: 77.5265 },
        basePrice: 2000,
        rating: 4.8,
        popularity: 94,
        accessible: true,
        timeSlots: ["6:00 PM"],
        icon: "🎤"
    },
    {
        id: 10,
        title: "Biswa Kalyan Rath",
        genre: "comedy",
        subGenre: "Stand-up Comedy",
        language: "English/Hindi",
        venue: "Good Shepherd Auditorium",
        address: "Museum Road",
        location: { lat: 12.9787, lng: 77.6053 },
        basePrice: 600,
        rating: 4.3,
        popularity: 76,
        accessible: false,
        timeSlots: ["6:00 PM", "8:30 PM"],
        icon: "😂"
    },
    {
        id: 11,
        title: "Jailer",
        genre: "movie",
        subGenre: "Action/Comedy",
        language: "Tamil",
        venue: "Cinepolis Nexus Shantiniketan",
        address: "Whitefield",
        location: { lat: 12.9698, lng: 77.7499 },
        basePrice: 200,
        rating: 4.4,
        popularity: 87,
        accessible: true,
        timeSlots: ["10:00 AM", "1:00 PM", "4:00 PM", "7:00 PM"],
        icon: "🎬"
    },
    {
        id: 12,
        title: "The Piano Guys",
        genre: "concert",
        subGenre: "Classical/Pop",
        language: "Instrumental",
        venue: "Bangalore International Centre",
        address: "Domlur",
        location: { lat: 12.9611, lng: 77.6387 },
        basePrice: 1200,
        rating: 4.6,
        popularity: 72,
        accessible: true,
        timeSlots: ["7:00 PM"],
        icon: "🎤"
    },
    {
        id: 13,
        title: "The Tempest",
        genre: "theatre",
        subGenre: "Shakespeare",
        language: "English",
        venue: "Jagriti Theatre",
        address: "Whitefield",
        location: { lat: 12.9781, lng: 77.7287 },
        basePrice: 400,
        rating: 4.5,
        popularity: 58,
        accessible: true,
        timeSlots: ["4:00 PM", "7:30 PM"],
        icon: "🎭"
    },
    {
        id: 14,
        title: "India vs Australia T20",
        genre: "sports",
        subGenre: "Cricket - International",
        language: "Multi",
        venue: "M. Chinnaswamy Stadium",
        address: "Cubbon Park, MG Road",
        location: { lat: 12.9789, lng: 77.5996 },
        basePrice: 1000,
        rating: 4.8,
        popularity: 96,
        accessible: true,
        timeSlots: ["7:00 PM"],
        icon: "🏏"
    },
    {
        id: 15,
        title: "Leo",
        genre: "movie",
        subGenre: "Action/Thriller",
        language: "Tamil",
        venue: "PVR Phoenix Marketcity",
        address: "Whitefield",
        location: { lat: 12.9980, lng: 77.6963 },
        basePrice: 280,
        rating: 4.3,
        popularity: 90,
        accessible: true,
        timeSlots: ["11:00 AM", "2:30 PM", "6:00 PM", "9:30 PM"],
        icon: "🎬"
    },
    {
        id: 16,
        title: "Kenny Sebastian",
        genre: "comedy",
        subGenre: "Stand-up Comedy",
        language: "English/Hindi",
        venue: "Kanteerava Indoor Stadium",
        address: "Kasturba Road",
        location: { lat: 12.9785, lng: 77.5933 },
        basePrice: 700,
        rating: 4.5,
        popularity: 79,
        accessible: true,
        timeSlots: ["7:00 PM", "9:00 PM"],
        icon: "😂"
    },
    {
        id: 17,
        title: "Bangalore Blues Festival",
        genre: "concert",
        subGenre: "Blues/Jazz",
        language: "Instrumental",
        venue: "Lalit Ashok",
        address: "Kumara Krupa Road",
        location: { lat: 12.9981, lng: 77.5834 },
        basePrice: 1800,
        rating: 4.7,
        popularity: 68,
        accessible: true,
        timeSlots: ["6:00 PM"],
        icon: "🎤"
    },
    {
        id: 18,
        title: "Barbie",
        genre: "movie",
        subGenre: "Comedy/Fantasy",
        language: "English",
        venue: "INOX Garuda Mall",
        address: "Magrath Road",
        location: { lat: 12.9721, lng: 77.6204 },
        basePrice: 320,
        rating: 4.4,
        popularity: 83,
        accessible: true,
        timeSlots: ["10:30 AM", "1:00 PM", "4:00 PM", "7:00 PM"],
        icon: "🎬"
    },
    {
        id: 19,
        title: "BengaluRu Premier League",
        genre: "sports",
        subGenre: "Football",
        language: "Multi",
        venue: "Bangalore Football Stadium",
        address: "Mallathahalli",
        location: { lat: 12.9569, lng: 77.5126 },
        basePrice: 150,
        rating: 4.1,
        popularity: 62,
        accessible: true,
        timeSlots: ["5:00 PM"],
        icon: "⚽"
    },
    {
        id: 20,
        title: "Namma Theatre Comedy",
        genre: "theatre",
        subGenre: "Comedy Play",
        language: "Kannada",
        venue: "Ravindra Kalakshetra",
        address: "JC Road",
        location: { lat: 12.9612, lng: 77.5840 },
        basePrice: 250,
        rating: 4.2,
        popularity: 55,
        accessible: false,
        timeSlots: ["3:00 PM", "6:30 PM"],
        icon: "🎭"
    }
];

// Default user location (Bangalore city center)
const defaultUserLocation = {
    lat: 12.9716,
    lng: 77.5946,
    name: "Bangalore"
};
